### PR TITLE
Update es.xml

### PR DESCRIPTION
**Pull request by Jhovany200**
Update the translation

### CODE REVIEW

**Comment by mingkuang-Chuyu** [comment]
Update now~~
but the CompactOS called by MS. So, keep "CompactOS" .

**Comment by verdy-p** [comment]
MS uses an API internally using "CompactOS" but its documentation on MSDN translates the term for descriptive use in the GUI. It's safe to translate it when the term is found in MSDN itself and does not refer to an internal API used by code only.

Users of DISM++ don't care about these internal technical details as long as they know what they clearly are refering to. Windows has many translated terms for the GUI, we should use them according to what we see in its own interface (including on the console tools) or online in Microsoft support sites, because tusers will take more clever decisions if they better understand the terms. Otherwise DISM++ would only be in English (and not even in Chinese like what you are developing!)

**Comment by mingkuang-Chuyu** [comment]
But the user will not be so, they are eager to know what this is.  If not named "CompactOS" they do not know what this stuff. 

Atlaset in Windows 10 the Feature called "CompactOS" in CUI.

**Comment by mingkuang-Chuyu** [comment]
Like UEFI, in China we called UEFI also,  we will not call it for "统一的可扩展固件接口".  This is because the translation will often cause ambiguity, and even eventually lead to everyone do not know what it is.

**Pull request merged**
