### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Jhovany200**
You can add detection of all languages, it only works ./en/index.html
You can enable all languages

### CODE REVIEW

**Comment by Jhovany200** [comment]
I am a beginner, I just want to automatically detect my language
sorry for my English.

**Comment by Jhovany200** [comment]
If you can, enable automatic detection of all languages, Thank

**Comment by Jhovany200** [comment]
I wanted to try the English, but it was modified for Spanish, to see if it worked.
example:
else
    la='./en/index.html';

my added:
else
    la='./es/index.html';

This is by default in the repository.

"sorry for my English".

**Comment by mingkuang-Chuyu** [comment]
The es support now

**Pull request closed without merging**
